# Generated by Django 5.1.7 on 2025-03-11 20:36

from django.db import migrations

def populate_plan_choice(apps, schema_editor):
    PlanChoice = apps.get_model('client', 'PlanChoice')
    PlanChoice.objects.create(
        plan='ST',
        name='Standard',
        cost='3.00',
        is_active=True,
        description1='Get access to standard articles and reports',
        description2='Limited Access',
        external_plan_id='P-51D757671A461943SM7IQFQA',
        external_api_url='https://www.paypal.com/sdk/js?client-id=AWm-h-cl6lxMbX86IKoN95105Zr0AwMAMn3HxizJeB7yuBVgJ99X6XB87q4yalG_LW_LUljiLCUtY4Lg&vault=true&intent=subscription',
        external_style_json="""{
            "shape": "pill",
            "color": "blue",
            "layout": "vertical",
            "label": "subscribe"     
}
"""
    )
    
    PlanChoice.objects.create(
        plan='PR',
        name='Premium',
        cost='9.00',
        is_active=True,
        description1='Highly regarded premium articles and reports',
        description2='Full Access',
        external_plan_id='P-3CR667383J875900CM7IQGGQ',
        external_api_url='https://www.paypal.com/sdk/js?g&vault=true&intent=subscription',
        external_style_json="""{
            "shape": "pill",
            "color": "gold",
            "layout": "vertical",
            "label": "subscribe"     
}
"""
    )


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_planchoice_alter_subscription_cost'),
    ]

    operations = [
        migrations.RunPython(populate_plan_choice)
    ]
